### ISSUE TITLE
Caching überlegen

### ISSUE THREAD

**Issue by olid901** [olid901/ShakerApp#3]
Caching Konzept: Bilder, Favoriten und Objekte in der einkaufsliste werden persistent abgespeichert.

Persistentes Speichern von Objekten: https://mkyong.com/java/how-to-read-and-write-java-object-to-a-file/

**Comment by c-schuhmann** [comment]
Prüfen: Wie funktioniert das Caching in OkHttp?
- Wie wird es eingerichtet
- Wo wird alles gespeichert
- Wie lang werden Daten gespeichert
- Wie werden gecachte Daten abgerufen
- Wie wird der Cache gelöscht
- (sonstiges)
