### ISSUE TITLE
Drawer Menu

### ISSUE THREAD

**Issue by olid901** [olid901/ShakerApp#4]

**Comment by c-schuhmann** [comment]
Kleines Drop-Down Menü (oder Drawer) mit verscheidenen Unterpunkten, Vorschläge für den Anfang:
- Startseite (bzw. Suche)
- Favoriten
- Einstellungen

**Comment by c-schuhmann** [comment]
Eine Grundversion des Drawers wurde hinzugefügt, genauere Änderungen werden später vorgenommen.
