### ISSUE TITLE
Measurements magic

### ISSUE THREAD

**Issue by olid901** [olid901/ShakerApp#6]
Nachdem ich mir Regex angeschaut habe hasse ich nun endgültig mein Leben aber hier ist nen Ausdruck der alle möglichen Mengenangaben in oz erkennt:
- gesamte auswahl: ([0-9]+ )?([0-9].)?[0-9] oz
- Auswahl nur der Mengenangabe: ([0-9]+ )?([0-9].)?[0-9](?= oz)
- Auswahl von Brüchen: [0-9]/[0-9](?= oz)
- Auswahl von Kommazahlen im Bereich 0-1: 0[\.,][0-9]+(?= oz)
- Auswahl einer (optionalen) Ganzzahl gefolgt von Lehrzeichen und Dezimalkommazahl im Bereich 0-1: ([0-9]+ )?0[\.,][0-9](?= oz)

Vorgehensweise:
1. Auswahl von Brüchen
2. Brüche in dezimal umrechnen (Wertebereich ist 0-1)
3. Wert aus 2 auf Vorstehende Zahl rechnen (wenn vorhanden)
4. Umrechnen in cl mit Rundung auf 0.5cl

**Comment by c-schuhmann** [comment]
Zutaten werden oft in FREEDOM UNITS © gemessen, die sollen (nach Möglichkeit) in metrische Einheiten umgewandelt werden
